#!/bin/zsh
## alias for alias in /u/epitech_2014/plenar_d/cu
## 
## Made by damien plenard
## Login   <plenar_d@epitech.net>
## 
## Started on  Tue May 25 14:07:58 2010 damien plenard
## Last update Wed Dec 21 23:56:49 2011 Damien Plenard
##

alias ls='ls -Fh'
alias l='ls -l'
alias la='ls -la'
alias ne='emacs -nw'
alias j='jobs'
alias grep="grep"
alias mkdir='nocorrect mkdir -p'
alias find='noglob find'
alias jogsoul="~/.jogsoul.d/jogsoul ~/.jogsoul"

if [ -d ~/.git-achievements ]
then
    alias git="git-achievements"
fi

alias reload="source ~/.zshrc && echo \"$fg[green]Sourced ~/.zshrc$fg[default]\""
alias gnus='emacs -f gnus'
alias tmux="if tmux has; then tmux attach; else tmux new; fi"

if [ ${USER} = "plenar_d" ]
then
    alias bye='kdestroy;kill -9 -1'
    alias msg='ns_send_msg'
else
    alias bye='kill -9 -1'
fi
