#!/bin/zsh
## alias for alias in /u/epitech_2014/plenar_d/cu
## 
## Made by damien plenard
## Login   <plenar_d@epitech.net>
## 
## Started on  Tue May 25 14:07:58 2010 damien plenard
## Last update Mon Oct 15 13:47:59 2012 Damien Plenard
##

alias ls='ls -Fh'
alias l='ls++ -Fhl'
alias la='ls++ -Fhla'
alias ne='emacs -nw'
alias j='jobs'
alias grep="grep --color"
alias mkdir='nocorrect mkdir -p'
alias find='noglob find'
alias jogsoul="~/.jogsoul.d/jogsoul.pl ~/.jogsoul"
alias open="gnome-open"

if [ -d ~/.git-achievements ]
then
    alias git="git-achievements"
fi

alias reload="source ~/.zshrc && echo \"$fg[green]Sourced ~/.zshrc$fg[default]\""
alias gnus='emacs -f gnus'
#alias tmux="if tmux has; then tmux attach; else tmux new; fi"

# if [ ${USER} = "plenar_d" ]
# then
#     alias bye='kdestroy;kill -9 -1'
#     alias msg='ns_send_msg'
# else
#     alias bye='kill -9 -1'
# fi
