#!/bin/zsh
## alias for alias in /u/epitech_2014/plenar_d/cu
## 
## Made by damien plenard
## Login   <plenar_d@epitech.net>
## 
## Started on  Tue May 25 14:07:58 2010 damien plenard
## Last update Fri Sep 10 17:23:47 2010 damien plenard
##

alias ls='ls -Fh'
alias l='ls -l'
alias la='ls -la'
alias ne='emacs -nw'
alias j='jobs'
alias reload=". ${HOME}/.zshrc"
alias mkdir='nocorrect mkdir -p'
alias find='noglob find'


if [ ${USER} = "plenar_d" ]
then
    alias bye='kdestroy;kill -9 -1'
    alias msg='ns_send_msg'
else
    alias bye='sudo shutdown now'
fi
