#!/bin/zsh
## bindkey for bindkey in /u/epitech_2014/plenar_d/cu
## 
## Made by damien plenard
## Login   <plenar_d@epitech.net>
## 
## Started on  Tue May 25 14:07:58 2010 damien plenard
## Last update Fri Dec 10 20:05:36 2010 Damien Plenard
##

bindkey -e
autoload -U tetris
zle -N tetris
bindkey ^T tetris

autoload -U   edit-command-line
zle -N        edit-command-line
bindkey '\ee' edit-command-line

autoload zkbd
function zkbd_file() {
    [[ -f ~/.zkbd/${TERM}-${VENDOR}-${OSTYPE} ]] && printf '%s' ~/".zkbd/${TERM}-${VENDOR}-${OSTYPE}" && return 0
    [[ -f ~/.zkbd/${TERM}-${DISPLAY}          ]] && printf '%s' ~/".zkbd/${TERM}-${DISPLAY}"          && return 0
    return 1
}

if [ ${TERM} = "xterm" ] || [ ${TERM} = "screen" ]
then
    key[F1]='^[OP'
    key[F2]='^[OQ'
    key[F3]='^[OR'
    key[F4]='^[OS'
    key[F5]='^[[15~'
    key[F6]='^[[17~'
    key[F7]='^[[18~'
    key[F8]='^[[19~'
    key[F9]='^[[20~'
    key[F10]='^[[21~'
    key[F11]='^[[23~'
    key[F12]='^[[24~'
    key[Backspace]='^H'
    key[Insert]='^[[2~'
    key[Home]='^[[H'
    key[PageUp]='^[[5~'
    key[Delete]='^[[3~'
    key[End]='^[[F'
    key[PageDown]='^[[6~'
    key[Up]='^[[A'
    key[Left]='^[[D'
    key[Down]='^[[B'
    key[Right]='^[[C'
    key[Menu]='^[[29~'
fi
if [[ ${ret} -eq 0 ]] ; then
    source "${keyfile}"
else
    printf 'Failed to setup keys using zkbd.\n'
fi
unfunction zkbd_file; unset keyfile ret

# setup key accordingly
[[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
[[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
[[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode
[[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char
[[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-history
[[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-history
[[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char
[[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char
