#!/bin/zsh
## complete for complete in /u/epitech_2014/plenar_d/cu
## 
## Made by damien plenard
## Login   <plenar_d@epitech.net>
## 
## Started on  Tue May 25 14:07:58 2010 damien plenard
## Last update Wed Aug 25 11:17:49 2010 damoun
##

## killall
zstyle '*:processes-names' command 'ps -e -o comm='

## kill 
zstyle '*:processes' command 'ps -au$USER'
zstyle '*:**:processes' list-colors '=(#b]) #([0-9]#)*=0=01;32'