#!/bin/zsh
## module for module in /u/epitech_2014/plenar_d/cu
## 
## Made by damien plenard
## Login   <plenar_d@epitech.net>
## 
## Started on  Tue May 25 14:07:58 2010 damien plenard
## Last update Wed Aug 25 14:26:35 2010 damien plenard
##

zmodload zsh/compctl
zmodload zsh/complist
zmodload zsh/datetime
zmodload zsh/mathfunc
zmodload zsh/stat
zmodload zsh/system
zmodload zsh/zftp

autoload -U colors && colors