#!/bin/zsh
## opt for options in /u/epitech_2014/plenar_d/cu
## 
## Made by damien plenard
## Login   <plenar_d@epitech.net>
## 
## Started on  Tue May 25 14:07:58 2010 damien plenard
## Last update Tue Aug 24 17:40:27 2010 damien plenard
##

######################################################################
###
### Options (man zshoptions)
###
######################################################################

######################################################################
##
## Changing Directories
##
######################################################################

setopt CHASE_DOTS
setopt CHASE_LINKS

######################################################################
##
## Completion
##
######################################################################

setopt ALWAYS_LAST_PROMPT
setopt AUTO_LIST
setopt AUTO_MENU
setopt LIST_AMBIGUOUS
setopt ALWAYS_TO_END
setopt AUTO_PARAM_SLASH
setopt COMPLETE_ALIASES
setopt COMPLETE_IN_WORD
unsetopt LIST_BEEP
setopt LIST_TYPES
setopt REC_EXACT

######################################################################
##
## History
##
######################################################################

setopt APPEND_HISTORY
setopt BANG_HIST
setopt EXTENDED_HISTORY
unsetopt HIST_BEEP
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt SHARE_HISTORY

######################################################################
##
## Initialisation
##
######################################################################

unsetopt ALL_EXPORT
unsetopt GLOBAL_RCS

######################################################################
##
## Input/Output
##
######################################################################

setopt ALIASES
setopt PRINT_EXIT_VALUE
setopt SUN_KEYBOARD_HACK

######################################################################
##
## Job Control
##
######################################################################

setopt AUTO_CONTINUE
setopt AUTO_RESUME
setopt CHECK_JOBS
setopt BG_NICE
setopt LONG_LIST_JOBS
setopt NOTIFY

######################################################################
##
## Prompting
##
######################################################################

setopt TRANSIENT_RPROMPT
setopt PROMPT_PERCENT

######################################################################
##
## Scripts and Functions
##
######################################################################

setopt C_BASES
setopt FUNCTION_ARGZERO

######################################################################
##
## Shell Emulation
##
######################################################################

setopt BSD_ECHO

######################################################################
##
## Zle
##
######################################################################

unsetopt BEEP
setopt EMACS
setopt ZLE
