#!/bin/zsh
## .zshrc for path in /u/epitech_2014/plenar_d/cu
## 
## Made by damien plenard
## Login   <plenar_d@epitech.net>
## 
## Started on  Tue May 25 14:07:58 2010 damien plenard
## Last update Mon Dec 13 12:10:27 2010 Damien Plenard
##

# Package
export PATH="/usr/local/sbin:/usr/local/bin"
# System
export PATH="${PATH}:/usr/sbin:/usr/bin:/sbin:/bin"

# git-achivement
export PATH="${PATH}:${HOME}/.git-achievements"

if [ ${HOST} = "maya.epitech.net" -o ${HOST} = "inca.epitech.net" ]
then
    export PATH="${PATH}:/usr/sfw/bin:/usr/sfw/sbin"
elif [ ${USER} = "plenar_d" ]
then
# Bocal
    export PATH="${PATH}:/usr/site/sbin:/usr/site/bin"
# NetSoul
    export PATH="${PATH}:/usr/netsoul/sbin:/usr/netsoul/bin"
# Heimdal
    export PATH="${PATH}:/usr/heimdal/sbin:/usr/heimdal/bin"
# Arla
    export PATH="${PATH}:/usr/arla/sbin:/usr/arla/bin"
fi
