skip_global_compinit=1

export DOTFILES=$HOME/.dotfiles
export REPORTTIME="3"
export TOUCHBAR_GIT_ENABLED="true"
export ZSH_DISABLE_COMPFIX="false"
export TMUX_PLUGIN_MANAGER_PATH=~/.tmux/plugins
export YSU_MESSAGE_POSITION="after"
