source $DOTFILES/zsh/aliases
source $DOTFILES/zsh/functions

autoload -Uz compinit
if [[ -n ~/.zcompdump(#qN.mh+24) ]]; then
  compinit
  touch .zcompdump
else
  compinit -C
fi

source $DOTFILES/zsh/antidote/antidote.zsh
antidote load
