#!/bin/zsh
## .zshrc for zshrc in /u/epitech_2014/plenar_d/cu
## 
## Made by damien plenard
## Login   <plenar_d@epitech.net>
## 
## Started on  Tue May 25 14:07:58 2010 damien plenard
## Last update Tue Sep 20 14:49:47 2011 Damien Plenard
##

if [ -f $HOME/.zsh.d/vers ]; then
    . $HOME/.zsh.d/vers
fi

if [ -f $HOME/.zsh.d/env ]; then
    . $HOME/.zsh.d/env
fi

if [ -f $HOME/.zsh.d/path ]; then
    . $HOME/.zsh.d/path
fi

if [ -f $HOME/.zsh.d/opt ]; then
    . $HOME/.zsh.d/opt
fi

if [ -f $HOME/.zsh.d/alias ]; then
    . $HOME/.zsh.d/alias
fi

if [ -f $HOME/.zsh.d/function ]; then
    . $HOME/.zsh.d/function
fi

if [ -f $HOME/.zsh.d/bindkey ]; then
    . $HOME/.zsh.d/bindkey
fi

if [ -f $HOME/.zsh.d/module ]; then
    . $HOME/.zsh.d/module
fi

if [ -f $HOME/.zsh.d/complete ]; then
    . $HOME/.zsh.d/complete
fi
